
name: ppb_testing_assignment
description: A Flutter app for comprehensive testing assignment (REST API & Offline-First SQLite)
environment:
  sdk: '^3.9.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  integration_test:
    sdk: flutter
  sqflite_common_ffi: ^2.4.0
dependencies:
  http: ^1.6.0
  provider: ^6.1.5+1
  sqflite: ^2.4.2
